# To-Do : The below hardcoded values must be taken from the environment variables in file located under 

spring:
    application:
        name: account-core
        
    datasource:
        account:
            url: jdbc:mariadb://localhost:3306
            username: spring_dev
            password: spring_dev
            driverClassName: org.mariadb.jdbc.Driver
        
        hikari:
            connection-init-sql: 
            maximum-pool-size:

